//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanZi.Web.ceping {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtEvaluation;
		protected global::System.Web.UI.WebControls.TextBox txtSubUID;
		protected global::System.Web.UI.WebControls.TextBox txtSubIP;
		protected global::System.Web.UI.WebControls.TextBox txtSubTime;
		protected global::System.Web.UI.WebControls.TextBox txtOptionChecked;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new SanZi.Web.MasterPage Master {
            get {
                return ((SanZi.Web.MasterPage)(base.Master));
            }
        }
    }
}
