//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanZi.Web.usertitle {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblTitleID;
	protected global::System.Web.UI.WebControls.Label lblTitleName;
	protected global::System.Web.UI.WebControls.Label lblTitleDesc;
	protected global::System.Web.UI.WebControls.Label lblSubTime;
	protected global::System.Web.UI.WebControls.Label lblSubUID;
	protected global::System.Web.UI.WebControls.Label lblDelFlag;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new SanZi.Web.MasterPage Master {
            get {
                return ((SanZi.Web.MasterPage)(base.Master));
            }
        }
    }
}
